import { decrypt, encrypt } from "@/utils/crypto";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const CryptoTest: NextPage = () => {
  const [message, setMessage] = useState("")
  const [secret, setSecret] = useState("")
  const [encrypted, setEncrypted] = useState<Uint8Array>()
  const [decrypted, setDecrypted] = useState<string>()

  const onEncrypt = async () => {
    const data = await encrypt(new TextEncoder().encode(message), secret);
    setEncrypted(data)
  }

  const onDecrypt = async () => {
    if (!encrypted) return
    const data = await decrypt(encrypted, secret);
    setDecrypted(new TextDecoder().decode(data))
  }

  return (
    <>
      <Head>
        <title>CryptoTest</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#96f364] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <input
            onChange={(e) => setMessage(e.target.value)}
            placeholder="Message"
            type="text" className="bg-[#15162c] text-[#a7f974] px-4 py-2 rounded-md shadow-md hover:bg-[#a7f974] hover:text-[#15162c] transition duration-300 ease-in-out" />

          <input
            onChange={(e) => setSecret(e.target.value)}
            placeholder="Secret"
            type="text" className="bg-[#15162c] text-[#a7f974] px-4 py-2 rounded-md shadow-md hover:bg-[#a7f974] hover:text-[#15162c] transition duration-300 ease-in-out" />

          <div>
            <button
              className="bg-[#15162c] text-[#a7f974] px-4 py-2 rounded-md shadow-md hover:bg-[#a7f974] hover:text-[#15162c] transition duration-300 ease-in-out"
              onClick={onEncrypt}
            >
              Encrypt
            </button>
            <span className="mx-4"></span>
            <button
              className="bg-[#15162c] text-[#a7f974] px-4 py-2 rounded-md shadow-md hover:bg-[#a7f974] hover:text-[#15162c] transition duration-300 ease-in-out"
              onClick={onDecrypt}
            >
              Decrypt
            </button>
          </div>
          <div className="flex flex-col gap-4">
            <p className="text-[#a7f974]">Encrypted: {encrypted}</p>
            <p className="text-[#a7f974]">Decrypted: {decrypted}</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default CryptoTest;
