name: Build Backend Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kdrop-backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login in to Docker Registry
        run: docker login ${{ secrets.DOCKER_IMAGE }} -u ${{ secrets.DOCKER_REGISTRY }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_IMAGE }}
